Search.appendIndex(
    [
                {
            "fqsen": "\\Aritmetica",
            "name": "Aritmetica",
            "summary": "",
            "url": "classes/Aritmetica.html"
        },                {
            "fqsen": "\\Aritmetica\u003A\u003Asuma\u0028\u0029",
            "name": "suma",
            "summary": "Suma\u0020los\u0020elementos\u0020de\u0020una\u0020operaci\u00F3n.",
            "url": "classes/Aritmetica.html#method_suma"
        },                {
            "fqsen": "\\Aritmetica\u003A\u003Aresta\u0028\u0029",
            "name": "resta",
            "summary": "Resta\u0020dos\u0020n\u00FAmeros.",
            "url": "classes/Aritmetica.html#method_resta"
        },                {
            "fqsen": "\\Aritmetica\u003A\u003Amultiplicacion\u0028\u0029",
            "name": "multiplicacion",
            "summary": "Multiplica\u0020los\u0020elementos\u0020de\u0020un\u0020arreglo.",
            "url": "classes/Aritmetica.html#method_multiplicacion"
        },                {
            "fqsen": "\\Aritmetica\u003A\u003Adivision\u0028\u0029",
            "name": "division",
            "summary": "Divide\u0020dos\u0020n\u00FAmeros.",
            "url": "classes/Aritmetica.html#method_division"
        },                {
            "fqsen": "\\Aritmetica\u003A\u003AgetUltimaResultado\u0028\u0029",
            "name": "getUltimaResultado",
            "summary": "Obtiene\u0020el\u0020\u00FAltimo\u0020resultado\u0020de\u0020una\u0020operaci\u00F3n\u0020aritm\u00E9tica.",
            "url": "classes/Aritmetica.html#method_getUltimaResultado"
        },                {
            "fqsen": "\\Aritmetica\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "Devuelve\u0020una\u0020representaci\u00F3n\u0020de\u0020cadena\u0020del\u0020\u00FAltimo\u0020resultado.",
            "url": "classes/Aritmetica.html#method___toString"
        },                {
            "fqsen": "\\Aritmetica\u003A\u003A\u0024ultimoResultado",
            "name": "ultimoResultado",
            "summary": "",
            "url": "classes/Aritmetica.html#property_ultimoResultado"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        }            ]
);
